version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo-saas:12.0
        command: odoo
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - ./sources/12.0:/home/odoo/src/repositories:ro
        environment:
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                pip install --user -r /home/odoo/src/repositories/foodcoops/requirements.txt

volumes:
    db:
    filestore:
