version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/openupgrade:12.0
        command: -- --stop-after-init
        depends_on:
            - db
        volumes:
            - ./sources/repositories:/home/odoo/src/repositories:ro
            - ./backups:/home/odoo/custom/backups:rw
        environment:
            PREVIOUS_DATABASE: mig-12.0
            DATABASE: &dbname final
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                # Installing requirements.txt
                for repo in /home/odoo/src/repositories/* ; do
                    if [ -f "$$repo/requirements.txt" ]; then
                        echo "Installing $$repo/requirements.txt.."
                        pip install --user --no-cache-dir -r $$repo/requirements.txt
                    fi
                done
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi
                # Last update all modules
                odoo --stop-after-init --update=all
                # Serve the final database backup
                click-odoo-backupdb --force $$DATABASE $$CUSTOM/backups/$$ODOO_VERSION.zip

volumes:
    db:
    filestore:
