version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/openupgrade:12.0
        depends_on:
            - db
        volumes:
            - ./sources/12.0:/home/odoo/src/repositories:ro
        environment:
            PREVIOUS_DATABASE: mig-11.0
            PGDATABASE: mig-12.0
            SAVE_BACKUP: 'true'

volumes:
    db:
    filestore:
