version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo:12.0
        command: odoo
        depends_on:
            - db
        ports:
            - "8069:8069"
        environment:
            DATABASE: &dbname mig-12.0
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                echo "Cloning repositories.."
                autoaggregate --config /home/odoo/custom/resources/repos.$$ODOO_VERSION.yml --install --output $$SOURCES/repositories
                /home/odoo/.resources/entrypoint.d/400-auto-detect-addons
                /home/odoo/.resources/entrypoint.d/500-config-generate

volumes:
    db:
    filestore:
