version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/openupgrade:12.0
        command: -- --stop-after-init
        depends_on:
            - db
        environment:
            PREVIOUS_DATABASE: mig-11.0
            DATABASE: &dbname mig-12.0
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                echo "Cloning repositories.."
                autoaggregate --config /home/odoo/custom/resources/repos.$$ODOO_VERSION.yml --install --output $$SOURCES/repositories
                /home/odoo/.resources/entrypoint.d/400-auto-detect-addons
                /home/odoo/.resources/entrypoint.d/500-config-generate
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi
                # Last update all modules
                odoo --stop-after-init --update=all
                # Serve the final database backup
                click-odoo-backupdb --force $$DATABASE $$CUSTOM/backups/$$ODOO_VERSION.zip

volumes:
    db:
    filestore:
