version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/openupgrade:10.0
        depends_on:
            - db
        volumes:
            - ./sources/10.0:/home/odoo/src/repositories:ro
        environment:
            STEP_NAME: mig-10.0
            #STEP_BACKUP: 'true'

volumes:
    db:
    filestore:
