version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo:11.0
        depends_on:
            - db
        volumes:
            - ./sources/openupgrade-11.0:/home/odoo/src/odoo
        environment:
            PREVIOUS_DATABASE: mig-10.0
            DATABASE: &dbname mig-11.0
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                echo "Replacing installed odoo with openupgrade.."
                pip install --user --no-cache-dir $$SOURCES/odoo
                # Always use an updated openugpradelib version
                pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi

volumes:
    db:
    filestore:
