version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo-foodcoops:9.0
        command: odoo
        depends_on:
            - db
        ports:
            - "8069:8069"
        environment:
            DATABASE: &dbname migrate
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e

volumes:
    db:
    filestore:
