version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo:12.0
        depends_on:
            - db
        volumes:
            - ./sources/12.0:/home/odoo/src/repositories:ro
        environment:
            STEP_NAME: final-12.0
            #STEP_BACKUP: 'true'
            SAVE_BACKUP: 'true'

volumes:
    db:
    filestore:
