version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo
        depends_on:
            - db

        image: druidoo/odoo:9.0
        volumes:
            - ./sources/openupgrade-9.0:/home/odoo/src/odoo
        environment:
            PREVIOUS_DATABASE: migrate
            DATABASE: &dbname mig-9.0
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                echo "Replacing installed odoo with openupgrade.."
                pip install --user --no-cache-dir $$SOURCES/odoo
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi

volumes:
    db:
    filestore:
