version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/openupgrade:9.0
        depends_on:
            - db
        volumes:
            - ./sources/9.0:/home/odoo/src/repositories:ro
        environment:
            PREVIOUS_DATABASE: migrate
            PGDATABASE: mig-9.0
            STEP_BACKUP: 'true'

volumes:
    db:
    filestore:
