version: '2.4'
services:

    db:
        image: postgres:10.6
        environment:
            POSTGRES_USER: odoo
            POSTGRES_PASSWORD: odoo
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - db:/var/lib/postgresql/data/pgdata

    odoo:
        image: druidoo/openupgrade:9.0
        command: -- --stop-after-init
        tty: true
        stdin_open: true

        environment:
            PGDATABASE: migrate
            WAIT_PG: 'true'
            LIST_DB: 'True'
            WORKERS: 0
            PROXY_MODE: 'false'
            FIXDBS: 'false'
            # 100 GB memory limit
            LIMIT_MEMORY_SOFT: 87374182400
            LIMIT_MEMORY_HARD: 107374182400
            # Openupgrade scripts
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                set -e
                /home/odoo/custom/scripts/common

        volumes:
            - ./scripts:/home/odoo/custom/scripts:ro
            - ./backups:/home/odoo/custom/backups:rw
            - filestore:/home/odoo/data

volumes:
    db:
    filestore:
