version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo:12.0
        depends_on:
            - db
        volumes:
            - ./sources/repositories:/home/odoo/src/repositories
        environment:
            PREVIOUS_DATABASE: mig-12.0
            DATABASE: &dbname final
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi

volumes:
    db:
    filestore:
