version: '2.4'
services:
    db:
        extends:
            file: docker-compose.common.yml
            service: db
    odoo:
        extends:
            file: docker-compose.common.yml
            service: odoo

        image: druidoo/odoo:12.0
        command: -- --stop-after-init
        depends_on:
            - db
        volumes:
            - ./sources/repositories:/home/odoo/src/repositories
            - ./backups:/home/odoo/custom/backups
        environment:
            PREVIOUS_DATABASE: final
            DATABASE: &dbname post
            PGDATABASE: *dbname
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                # Installing foodcoops requirements
                pip install --user --no-cache-dir -r /home/odoo/src/repositories/foodcoops/requirements.txt
                echo "Creating database backup: $$DATABASE"
                click-odoo-dropdb --if-exists $$DATABASE
                click-odoo-copydb -f $$PREVIOUS_DATABASE $$DATABASE
                # Run pre-migration script
                if [[ -f $$CUSTOM/scripts/pre-$$DATABASE ]]; then
                    echo "Running script: pre-$$DATABASE.."
                    $$CUSTOM/scripts/pre-$$DATABASE
                fi
                # Serve the final database backup
                click-odoo-backupdb --force $$DATABASE $$CUSTOM/backups/$$ODOO_VERSION.zip


volumes:
    db:
    filestore:
