#!/bin/bash
set -e

$CUSTOM/scripts/common.install_repo_requirements

# Installing latest openupgrade version
echo "Installing latest version of openupgradelib.."
pip install --user --ignore-installed git+https://github.com/OCA/openupgradelib.git@master

# Run pre-migration script
echo "Running pre-migration scripts.."
if [[ -f $CUSTOM/scripts/pre-$STEP_NAME ]]; then $CUSTOM/scripts/pre-$STEP_NAME; fi

# Update modules
odoo --stop-after-init --update=all

# Run post-migration script
echo "Running pre-migration scripts.."
if [[ -f $CUSTOM/scripts/post-$STEP_NAME ]]; then $CUSTOM/scripts/post-$STEP_NAME; fi

# Database Backup
if [[ "$STEP_BACKUP" == "true" ]]; then
	echo "Creating database backup: $STEP_NAME"
	click-odoo-dropdb --if-exists $STEP_NAME
	click-odoo-copydb -f $PGDATABASE $STEP_NAME
fi

# Save the database backup
if [ "$SAVE_BACKUP" == "true" ]; then
    click-odoo-backupdb --force $PGDATABASE $CUSTOM/backups/$STEP_NAME.zip
fi
