#!/bin/bash
set -e

$CUSTOM/scripts/common.install_repo_requirements

# Installing latest openupgrade version
echo "Installing latest version of openupgradelib.."
pip install --user --ignore-installed git+https://github.com/OCA/openupgradelib.git@master

# Database Backup
if [[ -f "$STEP_BACKUP" == "true" ]]; then
	echo "Creating database backup: $PGDATABASE"
	click-odoo-dropdb --if-exists $PGDATABASE
	click-odoo-copydb -f $PREVIOUS_DATABASE $PGDATABASE
fi

# Run pre-migration script
echo "Running pre-migration scripts.."
if [[ -f $CUSTOM/scripts/pre-$PGDATABASE ]]; then $CUSTOM/scripts/pre-$PGDATABASE; fi

# Update modules
odoo --stop-after-init --update=all

# Run post-migration script
echo "Running pre-migration scripts.."
if [[ -f $CUSTOM/scripts/post-$PGDATABASE ]]; then $CUSTOM/scripts/post-$PGDATABASE; fi

# Save the database backup
if [ "$SAVE_BACKUP" == "true" ]; then
    click-odoo-backupdb --force $PGDATABASE $CUSTOM/backups/$PGDATABASE.zip
fi
