#!/bin/bash
set -e

# Account Asset Management
# ------------------------
# Deactivate old account_asset module views
psql -c "UPDATE ir_ui_view SET active = False WHERE arch_fs ILIKE 'account_asset/%'"

# coop_account_check_deposit
# --------------------------
psql -c "UPDATE ir_model_data SET module = 'coop_account_check_deposit' WHERE module = 'account_check_deposit' AND model = 'account.journal'"

# coop_default_pricetag
# ---------------------
# module: coop_default_pricetag. Added records in ir_model_data which are deleted due to uninstalling of louve_custom_product module
# TODO: this has a fixed id. Not sure it'll work in other databases.
psql -c "INSERT INTO ir_model_data (id, create_uid, create_date, write_uid, write_date, noupdate, name, date_init, date_update, module, model, res_id) VALUES (nextval('ir_model_data_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 't', 'decimal_product_attribute_volume', (now() at time zone 'UTC'), (now() at time zone 'UTC'), 'coop_default_pricetag', 'decimal.precision', 7);"

# Migrate product print category
psql -c "ALTER TABLE product_category_print RENAME TO product_print_category"
psql -c "ALTER SEQUENCE product_category_print_id_seq RENAME TO product_print_category_id_seq"
psql -c "UPDATE ir_model_data SET model = 'product.print.category' WHERE model='product.category.print'"
psql -c "UPDATE ir_model_data SET name = 'ppc_demo_category' WHERE name='demo_category' AND model='product.print.category'"
psql -c "UPDATE ir_model_data SET name='ppc_demo_category' WHERE name='demo_category' AND model='product.print.category'"

# pos_access_rights
# -----------------
# res.groups xml IDs are changed in pos_access_right module
psql -c "update ir_model_data set name = 'group_negative_qty' where model='res.groups' and module = 'pos_access_right' and name = 'group_pos_negative_qty';"
psql -c "update ir_model_data set name = 'group_discount' where model='res.groups' and module = 'pos_access_right' and name = 'group_pos_discount';"
psql -c "update ir_model_data set name = 'group_change_unit_price' where model='res.groups' and module = 'pos_access_right' and name = 'group_pos_change_unit_price';"
psql -c "update ir_model_data set name = 'group_multi_order' where model='res.groups' and module = 'pos_access_right' and name = 'group_pos_multi_order';"
psql -c "update ir_model_data set name = 'group_delete_order' where model='res.groups' and module = 'pos_access_right' and name = 'group_pos_delete_order';"

# queue_jobs
# field name changed in queue.job model from channel to channel_method_name;
psql -c "ALTER TABLE queue_job RENAME COLUMN channel TO channel_method_name;"

# Post Clean
echo "Executing pre-$DATABASE-clean.py.."
$CUSTOM/scripts/pre-$DATABASE-clean.py
